### ISSUE TITLE
MMM-ROVA-trashcalendar

### ISSUE THREAD

**Issue by Peter2dronrijp** [jeroenpeters1986/MMM-ROVA-trashcalendar#4]
Module werkt niet. Melding kan MMM-ROVA-trashcalendar module niet vinden bij het opstarten van Magic mirror. Module is gewoon aanwezig.

[2024-10-03 12:42:05.157] [ERROR] (node:5130) UnhandledPromiseRejectionWarning: Error: Cannot find module 'request'
Require stack:
- /home/peter/MagicMirror/modules/MMM-ROVA-trashcalendar/node_helper.js
- /home/peter/MagicMirror/js/app.js
- /home/peter/MagicMirror/js/electron.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:121498)
    at Module._resolveFilename (/home/peter/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:1058:27)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/peter/MagicMirror/modules/MMM-ROVA-trashcalendar/node_helper.js:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at loadModule (/home/peter/MagicMirror/js/app.js:200:19)
(Use `electron --trace-warnings ...` to show where the warning was created)
[2024-10-03 12:42:05.158] [ERROR] (node:5130) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
.

**Comment by jeroenpeters1986** [comment]
Hoi @Peter2dronrijp, er staat dat het de module 'request' niet kan vinden. Heb je andere modules geinstalleerd die wel succesvol data ophalen van een externe bron?

**Comment by Peter2dronrijp** [comment]
Hallo Jeroen, bedankt voor je reactie.

Ik zal me even voorstellen.

Ik ben al gepensioneerd en 65 jaar.

Altijd in de elektronica gezeten en nog steeds.

Het blijft leuk.

 

Jazeker zoals, 

MMM-Buienradar

MMM-MyDutchWeather

MMM-RTSPStream

 

Ik ga overnieuw beginnen en ga het nog een keer proberen.

Heb een raspberry pi 5 gekocht.

 

Groetjes, Peter.

**Comment by jeroenpeters1986** [comment]
Hoi @Peter2dronrijp , leuk dat je je voorstelt! Altijd leuk om te weten wie de gebruikers zijn 👍 
Heel veel succes en als je nog issues tegenkomt, laat het hier gerust weten.

**Comment by Peter2dronrijp** [comment]
Nou Jeroen hij doet het echt niet, ook niet met de raspberry pi 5.

Krijg dus elke keer dezelfde melding dat hij de module niet kan vinden en start niet door.

Met andere modules heb ik geen probleem.

Groetjes, Peter.

 

                {

                   module: "MMM-ROVA-trashcalendar",

                        position: "top_center",

                        config: {

                                zipCode: "******",

                                houseNr: "1",

                                houseNrAddition: "a"

                        }

                },

**Comment by jeroenpeters1986** [comment]
Hoi @Peter2dronrijp, dank voor het uitzoeken en testen! Goed om te weten misschien, ik heb zelf mijn Magic Mirror niet operationeel op het moment. Wel heb ik gezien dat er wat wijzigingen zijn geweest in MagicMirror2 en dat bijv mijn module niet meer compatible is met de nieuw geinstalleerde MagicMirrors. Ik heb wel een idee wat er aan kan gebeuren, ik ga proberen daar deze week even wat tijd voor e maken. Ik houd je via dit issue op de hoogte van mijn vorderingen :-)

**Comment by Peter2dronrijp** [comment]
Fijn dat je dat wilt doen.

Groetjes, Peter Kruisman uit Dronryp.

**Comment by jeroenpeters1986** [comment]
Hoi @Peter2dronrijp ik heb zojuist een nieuwe update gemaakt. Zou je eens willen kijken of het werkt als je de module nogmaals installeert of update?

**Comment by Peter2dronrijp** [comment]
Hallo Jeroen, bedankt voor de update.

Ik ga het vandaag nog proberen.

Wel heb ik al ondervonden dat onze postcode 9035EZ niet werkt.

Dus zal ik hem met de postcode proberen die ingevuld staat.

Sorry voor de late reactie.

 

Groetjes, Peter.

**Comment by jeroenpeters1986** [comment]
Hoi @Peter2dronrijp geen probleem hoor wat betreft de reactietijd. De ROVA werkt niet in heel Nederland. Rova is een afvalverwerker die alleen afval inzamelt op deze locaties: https://www.rova.nl/over-ons#gemeenten Ik geloof niet dat Dronryp daar tussen staat, dus dat kan verklaren waarom het niet voor je werkt. Als de voorbeeldpostcode wel werkt weet ik in ieder dat de module weer compatible is met nieuwe versies van de MagicMirror haha

**Comment by Peter2dronrijp** [comment]
Hoi Jeroen,

 

Ik heb hem opnieuw geïnstalleerd en het volgende in config staan;

                {

                        module: "MMM-ROVA-trashcalendar",

                        position: "top_center",

                        config: {

                        zipCode: "8012AR",

                        houseNr: "90",

                        houseNrAddition: "a"

                }

                },

 

Helaas zie ik niets verschijnen op het scherm.

 

Groetjes, Peter.

 

Van: Jeroen Peters ***@***.*** 
Verzonden: zondag 13 oktober 2024 10:09
Aan: jeroenpeters1986/MMM-ROVA-trashcalendar
CC: Peter; Mention
Onderwerp: Re: [jeroenpeters1986/MMM-ROVA-trashcalendar] MMM-ROVA-trashcalendar (Issue #4)

 

Hoi @Peter2dronrijp <https://github.com/Peter2dronrijp>  ik heb zojuist een nieuwe update gemaakt. Zou je eens willen kijken of het werkt als je de module nogmaals installeert of update?

**Comment by jeroenpeters1986** [comment]
Oh dat is erg jammer @Peter2dronrijp . Krijg nu nog steeds die foutmelding over module requests not found, of laadt alles goed en komt er gewoon niets meer? Anders wordt het misschien tijd voor me om mijn eigen MagicMirror op te duiken 😬😬😬 die is al een tijdje in onbruik

**Comment by Peter2dronrijp** [comment]
Nee geen melding en helaas niets op het scherm.

De rest van de modules start wel gewoon op.

Zoals;

Alert

Google calender

Worldclock

Google assistant

Het weerbericht

Buienradar

Nu.nl

En het beeld van de voordeur bel/camera.

 

De afvalwijzer daar heb ik een api key voor gekregen.

Die werkt dan wel maar niet voor Dronryp.

 

Groetjes, Peter.

 

                            {

                                           module: 'MMM-Afvalwijzer',

                                           position: 'top_left',

                                           config: {

                                                         title:"Trash collection days",

                                                         apiKey:"5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca",

                                                         numberOfweeks:4,

                                                         houseNumber:"1",

                                                         postalCode:"3607LA",

                                                         streetName:"Valkenkamp",

                                                         extention:"",

                                                         showCleanprofsData: true,

                                                         showColorIcons:true,

                                                         showContainerIcons:true

                                           }

                            },

 

Van: Jeroen Peters ***@***.*** 
Verzonden: zaterdag 19 oktober 2024 13:48
Aan: jeroenpeters1986/MMM-ROVA-trashcalendar
CC: Peter; Mention
Onderwerp: Re: [jeroenpeters1986/MMM-ROVA-trashcalendar] MMM-ROVA-trashcalendar (Issue #4)

 

Oh dat is erg jammer @Peter2dronrijp <https://github.com/Peter2dronrijp>  . Krijg nu nog steeds die foutmelding over module requests not found, of laadt alles goed en komt er gewoon niets meer? Anders wordt het misschien tijd voor me om mijn eigen MagicMirror op te duiken 😬😬😬 die is al een tijdje in onbruik

**Comment by jeroenpeters1986** [comment]
Hoi @Peter2dronrijp  dank voor je inzet en je moeite zover. Ik heb inmiddels de module bijgewerkt en lokaal ook draaiend gehad. Mijn voorbeeld-adres moet tegenwoordig juist zonder de huisnumer toevoeging. Met 8012AR en huisnummer 90 doettie het bij mij wel helemaal.

**Comment by Peter2dronrijp** [comment]
Okido, ga ik nog even proberen.

 

Peter.

 

Van: Jeroen Peters ***@***.*** 
Verzonden: maandag 21 oktober 2024 09:17
Aan: jeroenpeters1986/MMM-ROVA-trashcalendar
CC: Peter; Mention
Onderwerp: Re: [jeroenpeters1986/MMM-ROVA-trashcalendar] MMM-ROVA-trashcalendar (Issue #4)

 

Hoi @Peter2dronrijp <https://github.com/Peter2dronrijp>  dank voor je inzet en je moeite zover. Ik heb inmiddels de module bijgewerkt en lokaal ook draaiend gehad. Mijn voorbeeld-adres moet tegenwoordig juist zonder de huisnumer toevoeging. Met 8012AR en huisnummer 90 doettie het bij mij wel helemaal.
